apiVersion: apps/v1
kind: Deployment
metadata:
 name: dotnetapp
 labels:
   app: dotnetapp
spec:
 replicas: 2
 selector:
   matchLabels:
    app: dotnetapp
 template:
    metadata:
      name:  dotnetapp-pod
      labels:
        app: dotnetapp
        tier: dev
    spec:
      containers:
      - name: dotnetapp
        image: docker89781/dotnet2:latest
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
spec:
  type: dotnetapp
  selector:
    app: dotnetapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080